# Generated by Django 5.2.15 on 2026-06-26 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('A', 'A - No funding'), ('B', 'B - Funding required')], max_length=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('on_hold', 'On hold'), ('merged', 'Merged')], default='pending', max_length=20)),
                ('committee_decision', models.CharField(blank=True, choices=[('proceed_independently', 'Proceed independently'), ('collaboration_recommended', 'Collaboration recommended'), ('hold', 'Hold'), ('search_insufficient', 'Search insufficient'), ('request_presentation', 'Request presentation'), ('combine_existing', 'Combine with existing'), ('enhance_search', 'Enhance search'), ('reject', 'Reject')], default='', max_length=30)),
                ('presentation_status', models.CharField(choices=[('not_requested', 'Not requested'), ('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='not_requested', max_length=20)),
                ('funding_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_required', max_length=20)),
                ('decision_reasoning', models.TextField(blank=True, default='')),
                ('decision_made_at', models.DateTimeField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, default='')),
                ('similar_projects_found', models.TextField(blank=True, default='')),
                ('differentiation', models.TextField(blank=True, default='')),
                ('collaboration_opportunities', models.TextField(blank=True, default='')),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('site_or_team', models.CharField(blank=True, default='', max_length=255)),
                ('tech_category', models.CharField(blank=True, choices=[('ai_ml', 'AI / ML'), ('automation', 'Automation'), ('business_process', 'Business process'), ('other', 'Other')], default='', max_length=20)),
                ('collaboration_interest', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('outcomes', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('phases', models.JSONField(blank=True, default=list)),
                ('funding_required', models.BooleanField(default=False)),
                ('personnel', models.TextField(blank=True, default='')),
                ('equipment', models.TextField(blank=True, default='')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_roi', models.TextField(blank=True, default='')),
                ('presentation_date', models.DateTimeField(blank=True, null=True)),
                ('presentation_requirements', models.TextField(blank=True, default='')),
                ('expected_resume_date', models.DateField(blank=True, null=True)),
                ('suggested_collaborators', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.request')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('on_hold', 'On hold'), ('merged', 'Merged')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('on_hold', 'On hold'), ('merged', 'Merged')], max_length=20, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='proposals.request')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
