# Generated by Django 5.2.15 on 2026-06-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('merged', 'Merged')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('merged', 'Merged')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('merged', 'Merged')], default='pending', max_length=20),
        ),
    ]
